name = "typescript-producer"
main = "src/index.mjs"
compatibility_date = "2022-06-23"

[build.upload]
format = "modules"

[vars]
KEY = "value"

[[queues.bindings]]
name = "QUEUE1"
type = "queue"
queue_name = "queue1"

[miniflare]
route = "http://127.0.0.1/*"
routes = ["api.mf/*"]