"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Extension = exports.Extension_Module = exports.TlsOptions = exports.TlsOptions_Version = exports.TlsOptions_Keypair = exports.HttpOptions = exports.HttpOptions_Header = exports.HttpOptions_Style = exports.DiskDirectory = exports.Network = exports.ExternalServer = exports.ExternalServer_Which = exports.ExternalServer_Https = exports.Worker = exports.Worker_Which = exports.Worker_DurableObjectStorage = exports.Worker_DurableObjectStorage_Which = exports.Worker_DurableObjectNamespace = exports.Worker_DurableObjectNamespace_Which = exports.Worker_Binding = exports.Worker_Binding_Which = exports.Worker_Binding_Parameter = exports.Worker_Binding_WrappedBinding = exports.Worker_Binding_CryptoKey = exports.Worker_Binding_CryptoKey_Which = exports.Worker_Binding_CryptoKey_Algorithm = exports.Worker_Binding_CryptoKey_Algorithm_Which = exports.Worker_Binding_CryptoKey_Usage = exports.Worker_Binding_DurableObjectNamespaceDesignator = exports.Worker_Binding_Type = exports.Worker_Binding_Type_Which = exports.Worker_Module = exports.Worker_Module_Which = exports.ServiceDesignator = exports.Service = exports.Service_Which = exports.Socket = exports.Socket_Which = exports.Socket_Https = exports.Config = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "e6afd26682091c01";
class Config extends capnp_ts_1.Struct {
    adoptServices(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownServices() { return capnp_ts_1.Struct.disown(this.getServices()); }
    getServices() { return capnp_ts_1.Struct.getList(0, Config._Services, this); }
    hasServices() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initServices(length) { return capnp_ts_1.Struct.initList(0, Config._Services, length, this); }
    setServices(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptSockets(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSockets() { return capnp_ts_1.Struct.disown(this.getSockets()); }
    getSockets() { return capnp_ts_1.Struct.getList(1, Config._Sockets, this); }
    hasSockets() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSockets(length) { return capnp_ts_1.Struct.initList(1, Config._Sockets, length, this); }
    setSockets(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptV8Flags(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownV8Flags() { return capnp_ts_1.Struct.disown(this.getV8Flags()); }
    getV8Flags() { return capnp_ts_1.Struct.getList(2, capnp.TextList, this); }
    hasV8Flags() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initV8Flags(length) { return capnp_ts_1.Struct.initList(2, capnp.TextList, length, this); }
    setV8Flags(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptExtensions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownExtensions() { return capnp_ts_1.Struct.disown(this.getExtensions()); }
    getExtensions() { return capnp_ts_1.Struct.getList(3, Config._Extensions, this); }
    hasExtensions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initExtensions(length) { return capnp_ts_1.Struct.initList(3, Config._Extensions, length, this); }
    setExtensions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "Config_" + super.toString(); }
}
exports.Config = Config;
Config._capnp = { displayName: "Config", id: "8794486c76aaa7d6", size: new capnp_ts_1.ObjectSize(0, 4) };
class Socket_Https extends capnp_ts_1.Struct {
    adoptOptions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownOptions() { return capnp_ts_1.Struct.disown(this.getOptions()); }
    getOptions() { return capnp_ts_1.Struct.getStruct(2, HttpOptions, this); }
    hasOptions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initOptions() { return capnp_ts_1.Struct.initStructAt(2, HttpOptions, this); }
    setOptions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptTlsOptions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownTlsOptions() { return capnp_ts_1.Struct.disown(this.getTlsOptions()); }
    getTlsOptions() { return capnp_ts_1.Struct.getStruct(3, TlsOptions, this); }
    hasTlsOptions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initTlsOptions() { return capnp_ts_1.Struct.initStructAt(3, TlsOptions, this); }
    setTlsOptions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "Socket_Https_" + super.toString(); }
}
exports.Socket_Https = Socket_Https;
Socket_Https._capnp = { displayName: "https", id: "de123876383cbbdc", size: new capnp_ts_1.ObjectSize(8, 5) };
var Socket_Which;
(function (Socket_Which) {
    Socket_Which[Socket_Which["HTTP"] = 0] = "HTTP";
    Socket_Which[Socket_Which["HTTPS"] = 1] = "HTTPS";
})(Socket_Which = exports.Socket_Which || (exports.Socket_Which = {}));
class Socket extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getAddress() { return capnp_ts_1.Struct.getText(1, this); }
    setAddress(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptHttp(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this));
    }
    disownHttp() { return capnp_ts_1.Struct.disown(this.getHttp()); }
    getHttp() {
        capnp_ts_1.Struct.testWhich("http", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(2, HttpOptions, this);
    }
    hasHttp() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initHttp() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(2, HttpOptions, this);
    }
    isHttp() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setHttp(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this));
    }
    getHttps() {
        capnp_ts_1.Struct.testWhich("https", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getAs(Socket_Https, this);
    }
    initHttps() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.getAs(Socket_Https, this);
    }
    isHttps() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setHttps() { capnp_ts_1.Struct.setUint16(0, 1, this); }
    adoptService(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownService() { return capnp_ts_1.Struct.disown(this.getService()); }
    getService() { return capnp_ts_1.Struct.getStruct(4, ServiceDesignator, this); }
    hasService() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initService() { return capnp_ts_1.Struct.initStructAt(4, ServiceDesignator, this); }
    setService(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "Socket_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Socket = Socket;
Socket.HTTP = Socket_Which.HTTP;
Socket.HTTPS = Socket_Which.HTTPS;
Socket._capnp = { displayName: "Socket", id: "9a0eba45530ee79f", size: new capnp_ts_1.ObjectSize(8, 5) };
var Service_Which;
(function (Service_Which) {
    Service_Which[Service_Which["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    Service_Which[Service_Which["WORKER"] = 1] = "WORKER";
    Service_Which[Service_Which["NETWORK"] = 2] = "NETWORK";
    Service_Which[Service_Which["EXTERNAL"] = 3] = "EXTERNAL";
    Service_Which[Service_Which["DISK"] = 4] = "DISK";
})(Service_Which = exports.Service_Which || (exports.Service_Which = {}));
class Service extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    isUnspecified() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setUnspecified() { capnp_ts_1.Struct.setUint16(0, 0, this); }
    adoptWorker(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownWorker() { return capnp_ts_1.Struct.disown(this.getWorker()); }
    getWorker() {
        capnp_ts_1.Struct.testWhich("worker", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(1, Worker, this);
    }
    hasWorker() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initWorker() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(1, Worker, this);
    }
    isWorker() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setWorker(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptNetwork(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownNetwork() { return capnp_ts_1.Struct.disown(this.getNetwork()); }
    getNetwork() {
        capnp_ts_1.Struct.testWhich("network", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getStruct(1, Network, this);
    }
    hasNetwork() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initNetwork() {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        return capnp_ts_1.Struct.initStructAt(1, Network, this);
    }
    isNetwork() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setNetwork(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptExternal(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownExternal() { return capnp_ts_1.Struct.disown(this.getExternal()); }
    getExternal() {
        capnp_ts_1.Struct.testWhich("external", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getStruct(1, ExternalServer, this);
    }
    hasExternal() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initExternal() {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        return capnp_ts_1.Struct.initStructAt(1, ExternalServer, this);
    }
    isExternal() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setExternal(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptDisk(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownDisk() { return capnp_ts_1.Struct.disown(this.getDisk()); }
    getDisk() {
        capnp_ts_1.Struct.testWhich("disk", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getStruct(1, DiskDirectory, this);
    }
    hasDisk() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initDisk() {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        return capnp_ts_1.Struct.initStructAt(1, DiskDirectory, this);
    }
    isDisk() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setDisk(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    toString() { return "Service_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Service = Service;
Service.UNSPECIFIED = Service_Which.UNSPECIFIED;
Service.WORKER = Service_Which.WORKER;
Service.NETWORK = Service_Which.NETWORK;
Service.EXTERNAL = Service_Which.EXTERNAL;
Service.DISK = Service_Which.DISK;
Service._capnp = { displayName: "Service", id: "e5c88e8bb7bcb6b9", size: new capnp_ts_1.ObjectSize(8, 2) };
class ServiceDesignator extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getEntrypoint() { return capnp_ts_1.Struct.getText(1, this); }
    setEntrypoint(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "ServiceDesignator_" + super.toString(); }
}
exports.ServiceDesignator = ServiceDesignator;
ServiceDesignator._capnp = { displayName: "ServiceDesignator", id: "ae8ec91cee724450", size: new capnp_ts_1.ObjectSize(0, 2) };
var Worker_Module_Which;
(function (Worker_Module_Which) {
    Worker_Module_Which[Worker_Module_Which["ES_MODULE"] = 0] = "ES_MODULE";
    Worker_Module_Which[Worker_Module_Which["COMMON_JS_MODULE"] = 1] = "COMMON_JS_MODULE";
    Worker_Module_Which[Worker_Module_Which["TEXT"] = 2] = "TEXT";
    Worker_Module_Which[Worker_Module_Which["DATA"] = 3] = "DATA";
    Worker_Module_Which[Worker_Module_Which["WASM"] = 4] = "WASM";
    Worker_Module_Which[Worker_Module_Which["JSON"] = 5] = "JSON";
})(Worker_Module_Which = exports.Worker_Module_Which || (exports.Worker_Module_Which = {}));
class Worker_Module extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getEsModule() {
        capnp_ts_1.Struct.testWhich("esModule", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isEsModule() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setEsModule(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    getCommonJsModule() {
        capnp_ts_1.Struct.testWhich("commonJsModule", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isCommonJsModule() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setCommonJsModule(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    getText() {
        capnp_ts_1.Struct.testWhich("text", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isText() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setText(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    adoptData(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownData() { return capnp_ts_1.Struct.disown(this.getData()); }
    getData() {
        capnp_ts_1.Struct.testWhich("data", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getData(1, this);
    }
    hasData() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initData(length) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        return capnp_ts_1.Struct.initData(1, length, this);
    }
    isData() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setData(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptWasm(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownWasm() { return capnp_ts_1.Struct.disown(this.getWasm()); }
    getWasm() {
        capnp_ts_1.Struct.testWhich("wasm", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getData(1, this);
    }
    hasWasm() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initWasm(length) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        return capnp_ts_1.Struct.initData(1, length, this);
    }
    isWasm() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setWasm(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    getJson() {
        capnp_ts_1.Struct.testWhich("json", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isJson() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setJson(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    toString() { return "Worker_Module_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Worker_Module = Worker_Module;
Worker_Module.ES_MODULE = Worker_Module_Which.ES_MODULE;
Worker_Module.COMMON_JS_MODULE = Worker_Module_Which.COMMON_JS_MODULE;
Worker_Module.TEXT = Worker_Module_Which.TEXT;
Worker_Module.DATA = Worker_Module_Which.DATA;
Worker_Module.WASM = Worker_Module_Which.WASM;
Worker_Module.JSON = Worker_Module_Which.JSON;
Worker_Module._capnp = { displayName: "Module", id: "d9d87a63770a12f3", size: new capnp_ts_1.ObjectSize(8, 2) };
var Worker_Binding_Type_Which;
(function (Worker_Binding_Type_Which) {
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["TEXT"] = 1] = "TEXT";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["DATA"] = 2] = "DATA";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["JSON"] = 3] = "JSON";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["WASM"] = 4] = "WASM";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["CRYPTO_KEY"] = 5] = "CRYPTO_KEY";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["SERVICE"] = 6] = "SERVICE";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["DURABLE_OBJECT_NAMESPACE"] = 7] = "DURABLE_OBJECT_NAMESPACE";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["KV_NAMESPACE"] = 8] = "KV_NAMESPACE";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["R2BUCKET"] = 9] = "R2BUCKET";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["R2ADMIN"] = 10] = "R2ADMIN";
    Worker_Binding_Type_Which[Worker_Binding_Type_Which["QUEUE"] = 11] = "QUEUE";
})(Worker_Binding_Type_Which = exports.Worker_Binding_Type_Which || (exports.Worker_Binding_Type_Which = {}));
class Worker_Binding_Type extends capnp_ts_1.Struct {
    isUnspecified() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setUnspecified() { capnp_ts_1.Struct.setUint16(0, 0, this); }
    isText() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setText() { capnp_ts_1.Struct.setUint16(0, 1, this); }
    isData() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setData() { capnp_ts_1.Struct.setUint16(0, 2, this); }
    isJson() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setJson() { capnp_ts_1.Struct.setUint16(0, 3, this); }
    isWasm() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setWasm() { capnp_ts_1.Struct.setUint16(0, 4, this); }
    adoptCryptoKey(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownCryptoKey() { return capnp_ts_1.Struct.disown(this.getCryptoKey()); }
    getCryptoKey() {
        capnp_ts_1.Struct.testWhich("cryptoKey", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getList(0, capnp.Uint16List, this);
    }
    hasCryptoKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initCryptoKey(length) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        return capnp_ts_1.Struct.initList(0, capnp.Uint16List, length, this);
    }
    isCryptoKey() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setCryptoKey(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    isService() { return capnp_ts_1.Struct.getUint16(0, this) === 6; }
    setService() { capnp_ts_1.Struct.setUint16(0, 6, this); }
    isDurableObjectNamespace() { return capnp_ts_1.Struct.getUint16(0, this) === 7; }
    setDurableObjectNamespace() { capnp_ts_1.Struct.setUint16(0, 7, this); }
    isKvNamespace() { return capnp_ts_1.Struct.getUint16(0, this) === 8; }
    setKvNamespace() { capnp_ts_1.Struct.setUint16(0, 8, this); }
    isR2Bucket() { return capnp_ts_1.Struct.getUint16(0, this) === 9; }
    setR2Bucket() { capnp_ts_1.Struct.setUint16(0, 9, this); }
    isR2Admin() { return capnp_ts_1.Struct.getUint16(0, this) === 10; }
    setR2Admin() { capnp_ts_1.Struct.setUint16(0, 10, this); }
    isQueue() { return capnp_ts_1.Struct.getUint16(0, this) === 11; }
    setQueue() { capnp_ts_1.Struct.setUint16(0, 11, this); }
    toString() { return "Worker_Binding_Type_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Worker_Binding_Type = Worker_Binding_Type;
Worker_Binding_Type.UNSPECIFIED = Worker_Binding_Type_Which.UNSPECIFIED;
Worker_Binding_Type.TEXT = Worker_Binding_Type_Which.TEXT;
Worker_Binding_Type.DATA = Worker_Binding_Type_Which.DATA;
Worker_Binding_Type.JSON = Worker_Binding_Type_Which.JSON;
Worker_Binding_Type.WASM = Worker_Binding_Type_Which.WASM;
Worker_Binding_Type.CRYPTO_KEY = Worker_Binding_Type_Which.CRYPTO_KEY;
Worker_Binding_Type.SERVICE = Worker_Binding_Type_Which.SERVICE;
Worker_Binding_Type.DURABLE_OBJECT_NAMESPACE = Worker_Binding_Type_Which.DURABLE_OBJECT_NAMESPACE;
Worker_Binding_Type.KV_NAMESPACE = Worker_Binding_Type_Which.KV_NAMESPACE;
Worker_Binding_Type.R2BUCKET = Worker_Binding_Type_Which.R2BUCKET;
Worker_Binding_Type.R2ADMIN = Worker_Binding_Type_Which.R2ADMIN;
Worker_Binding_Type.QUEUE = Worker_Binding_Type_Which.QUEUE;
Worker_Binding_Type._capnp = { displayName: "Type", id: "8906a1296519bf8a", size: new capnp_ts_1.ObjectSize(8, 1) };
class Worker_Binding_DurableObjectNamespaceDesignator extends capnp_ts_1.Struct {
    getClassName() { return capnp_ts_1.Struct.getText(0, this); }
    setClassName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getServiceName() { return capnp_ts_1.Struct.getText(1, this); }
    setServiceName(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "Worker_Binding_DurableObjectNamespaceDesignator_" + super.toString(); }
}
exports.Worker_Binding_DurableObjectNamespaceDesignator = Worker_Binding_DurableObjectNamespaceDesignator;
Worker_Binding_DurableObjectNamespaceDesignator._capnp = { displayName: "DurableObjectNamespaceDesignator", id: "804f144ff477aac7", size: new capnp_ts_1.ObjectSize(0, 2) };
var Worker_Binding_CryptoKey_Usage;
(function (Worker_Binding_CryptoKey_Usage) {
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["ENCRYPT"] = 0] = "ENCRYPT";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["DECRYPT"] = 1] = "DECRYPT";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["SIGN"] = 2] = "SIGN";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["VERIFY"] = 3] = "VERIFY";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["DERIVE_KEY"] = 4] = "DERIVE_KEY";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["DERIVE_BITS"] = 5] = "DERIVE_BITS";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["WRAP_KEY"] = 6] = "WRAP_KEY";
    Worker_Binding_CryptoKey_Usage[Worker_Binding_CryptoKey_Usage["UNWRAP_KEY"] = 7] = "UNWRAP_KEY";
})(Worker_Binding_CryptoKey_Usage = exports.Worker_Binding_CryptoKey_Usage || (exports.Worker_Binding_CryptoKey_Usage = {}));
var Worker_Binding_CryptoKey_Algorithm_Which;
(function (Worker_Binding_CryptoKey_Algorithm_Which) {
    Worker_Binding_CryptoKey_Algorithm_Which[Worker_Binding_CryptoKey_Algorithm_Which["NAME"] = 0] = "NAME";
    Worker_Binding_CryptoKey_Algorithm_Which[Worker_Binding_CryptoKey_Algorithm_Which["JSON"] = 1] = "JSON";
})(Worker_Binding_CryptoKey_Algorithm_Which = exports.Worker_Binding_CryptoKey_Algorithm_Which || (exports.Worker_Binding_CryptoKey_Algorithm_Which = {}));
class Worker_Binding_CryptoKey_Algorithm extends capnp_ts_1.Struct {
    getName() {
        capnp_ts_1.Struct.testWhich("name", capnp_ts_1.Struct.getUint16(2, this), 0, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isName() { return capnp_ts_1.Struct.getUint16(2, this) === 0; }
    setName(value) {
        capnp_ts_1.Struct.setUint16(2, 0, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    getJson() {
        capnp_ts_1.Struct.testWhich("json", capnp_ts_1.Struct.getUint16(2, this), 1, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isJson() { return capnp_ts_1.Struct.getUint16(2, this) === 1; }
    setJson(value) {
        capnp_ts_1.Struct.setUint16(2, 1, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    toString() { return "Worker_Binding_CryptoKey_Algorithm_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(2, this); }
}
exports.Worker_Binding_CryptoKey_Algorithm = Worker_Binding_CryptoKey_Algorithm;
Worker_Binding_CryptoKey_Algorithm.NAME = Worker_Binding_CryptoKey_Algorithm_Which.NAME;
Worker_Binding_CryptoKey_Algorithm.JSON = Worker_Binding_CryptoKey_Algorithm_Which.JSON;
Worker_Binding_CryptoKey_Algorithm._capnp = { displayName: "algorithm", id: "a1a040c5e00d7021", size: new capnp_ts_1.ObjectSize(8, 3) };
var Worker_Binding_CryptoKey_Which;
(function (Worker_Binding_CryptoKey_Which) {
    Worker_Binding_CryptoKey_Which[Worker_Binding_CryptoKey_Which["RAW"] = 0] = "RAW";
    Worker_Binding_CryptoKey_Which[Worker_Binding_CryptoKey_Which["HEX"] = 1] = "HEX";
    Worker_Binding_CryptoKey_Which[Worker_Binding_CryptoKey_Which["BASE64"] = 2] = "BASE64";
    Worker_Binding_CryptoKey_Which[Worker_Binding_CryptoKey_Which["PKCS8"] = 3] = "PKCS8";
    Worker_Binding_CryptoKey_Which[Worker_Binding_CryptoKey_Which["SPKI"] = 4] = "SPKI";
    Worker_Binding_CryptoKey_Which[Worker_Binding_CryptoKey_Which["JWK"] = 5] = "JWK";
})(Worker_Binding_CryptoKey_Which = exports.Worker_Binding_CryptoKey_Which || (exports.Worker_Binding_CryptoKey_Which = {}));
class Worker_Binding_CryptoKey extends capnp_ts_1.Struct {
    adoptRaw(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownRaw() { return capnp_ts_1.Struct.disown(this.getRaw()); }
    getRaw() {
        capnp_ts_1.Struct.testWhich("raw", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getData(0, this);
    }
    hasRaw() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initRaw(length) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initData(0, length, this);
    }
    isRaw() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setRaw(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    getHex() {
        capnp_ts_1.Struct.testWhich("hex", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isHex() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setHex(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getBase64() {
        capnp_ts_1.Struct.testWhich("base64", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isBase64() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setBase64(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getPkcs8() {
        capnp_ts_1.Struct.testWhich("pkcs8", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isPkcs8() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setPkcs8(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getSpki() {
        capnp_ts_1.Struct.testWhich("spki", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isSpki() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setSpki(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getJwk() {
        capnp_ts_1.Struct.testWhich("jwk", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isJwk() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setJwk(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getAlgorithm() { return capnp_ts_1.Struct.getAs(Worker_Binding_CryptoKey_Algorithm, this); }
    initAlgorithm() { return capnp_ts_1.Struct.getAs(Worker_Binding_CryptoKey_Algorithm, this); }
    getExtractable() { return capnp_ts_1.Struct.getBit(32, this, Worker_Binding_CryptoKey._capnp.defaultExtractable); }
    setExtractable(value) { capnp_ts_1.Struct.setBit(32, value, this); }
    adoptUsages(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownUsages() { return capnp_ts_1.Struct.disown(this.getUsages()); }
    getUsages() { return capnp_ts_1.Struct.getList(2, capnp.Uint16List, this); }
    hasUsages() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initUsages(length) { return capnp_ts_1.Struct.initList(2, capnp.Uint16List, length, this); }
    setUsages(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "Worker_Binding_CryptoKey_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Worker_Binding_CryptoKey = Worker_Binding_CryptoKey;
Worker_Binding_CryptoKey.RAW = Worker_Binding_CryptoKey_Which.RAW;
Worker_Binding_CryptoKey.HEX = Worker_Binding_CryptoKey_Which.HEX;
Worker_Binding_CryptoKey.BASE64 = Worker_Binding_CryptoKey_Which.BASE64;
Worker_Binding_CryptoKey.PKCS8 = Worker_Binding_CryptoKey_Which.PKCS8;
Worker_Binding_CryptoKey.SPKI = Worker_Binding_CryptoKey_Which.SPKI;
Worker_Binding_CryptoKey.JWK = Worker_Binding_CryptoKey_Which.JWK;
Worker_Binding_CryptoKey.Usage = Worker_Binding_CryptoKey_Usage;
Worker_Binding_CryptoKey._capnp = { displayName: "CryptoKey", id: "b5e1bff0e57d6eb0", size: new capnp_ts_1.ObjectSize(8, 3), defaultExtractable: capnp.getBitMask(false, 0) };
class Worker_Binding_WrappedBinding extends capnp_ts_1.Struct {
    getModuleName() { return capnp_ts_1.Struct.getText(0, this); }
    setModuleName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getEntrypoint() { return capnp_ts_1.Struct.getText(1, this, Worker_Binding_WrappedBinding._capnp.defaultEntrypoint); }
    setEntrypoint(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptInnerBindings(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownInnerBindings() { return capnp_ts_1.Struct.disown(this.getInnerBindings()); }
    getInnerBindings() { return capnp_ts_1.Struct.getList(2, Worker_Binding_WrappedBinding._InnerBindings, this); }
    hasInnerBindings() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initInnerBindings(length) { return capnp_ts_1.Struct.initList(2, Worker_Binding_WrappedBinding._InnerBindings, length, this); }
    setInnerBindings(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "Worker_Binding_WrappedBinding_" + super.toString(); }
}
exports.Worker_Binding_WrappedBinding = Worker_Binding_WrappedBinding;
Worker_Binding_WrappedBinding._capnp = { displayName: "WrappedBinding", id: "e6f066b75f0ea113", size: new capnp_ts_1.ObjectSize(0, 3), defaultEntrypoint: "default" };
class Worker_Binding_Parameter extends capnp_ts_1.Struct {
    adoptType(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownType() { return capnp_ts_1.Struct.disown(this.getType()); }
    getType() { return capnp_ts_1.Struct.getStruct(1, Worker_Binding_Type, this); }
    hasType() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initType() { return capnp_ts_1.Struct.initStructAt(1, Worker_Binding_Type, this); }
    setType(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getOptional() { return capnp_ts_1.Struct.getBit(16, this); }
    setOptional(value) { capnp_ts_1.Struct.setBit(16, value, this); }
    toString() { return "Worker_Binding_Parameter_" + super.toString(); }
}
exports.Worker_Binding_Parameter = Worker_Binding_Parameter;
Worker_Binding_Parameter._capnp = { displayName: "parameter", id: "dc57e1258d26d152", size: new capnp_ts_1.ObjectSize(8, 2) };
var Worker_Binding_Which;
(function (Worker_Binding_Which) {
    Worker_Binding_Which[Worker_Binding_Which["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    Worker_Binding_Which[Worker_Binding_Which["PARAMETER"] = 1] = "PARAMETER";
    Worker_Binding_Which[Worker_Binding_Which["TEXT"] = 2] = "TEXT";
    Worker_Binding_Which[Worker_Binding_Which["DATA"] = 3] = "DATA";
    Worker_Binding_Which[Worker_Binding_Which["JSON"] = 4] = "JSON";
    Worker_Binding_Which[Worker_Binding_Which["WASM_MODULE"] = 5] = "WASM_MODULE";
    Worker_Binding_Which[Worker_Binding_Which["CRYPTO_KEY"] = 6] = "CRYPTO_KEY";
    Worker_Binding_Which[Worker_Binding_Which["SERVICE"] = 7] = "SERVICE";
    Worker_Binding_Which[Worker_Binding_Which["DURABLE_OBJECT_NAMESPACE"] = 8] = "DURABLE_OBJECT_NAMESPACE";
    Worker_Binding_Which[Worker_Binding_Which["KV_NAMESPACE"] = 9] = "KV_NAMESPACE";
    Worker_Binding_Which[Worker_Binding_Which["R2BUCKET"] = 10] = "R2BUCKET";
    Worker_Binding_Which[Worker_Binding_Which["R2ADMIN"] = 11] = "R2ADMIN";
    Worker_Binding_Which[Worker_Binding_Which["WRAPPED"] = 12] = "WRAPPED";
    Worker_Binding_Which[Worker_Binding_Which["QUEUE"] = 13] = "QUEUE";
})(Worker_Binding_Which = exports.Worker_Binding_Which || (exports.Worker_Binding_Which = {}));
class Worker_Binding extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    isUnspecified() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setUnspecified() { capnp_ts_1.Struct.setUint16(0, 0, this); }
    getParameter() {
        capnp_ts_1.Struct.testWhich("parameter", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getAs(Worker_Binding_Parameter, this);
    }
    initParameter() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.getAs(Worker_Binding_Parameter, this);
    }
    isParameter() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setParameter() { capnp_ts_1.Struct.setUint16(0, 1, this); }
    getText() {
        capnp_ts_1.Struct.testWhich("text", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isText() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setText(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    adoptData(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownData() { return capnp_ts_1.Struct.disown(this.getData()); }
    getData() {
        capnp_ts_1.Struct.testWhich("data", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getData(1, this);
    }
    hasData() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initData(length) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        return capnp_ts_1.Struct.initData(1, length, this);
    }
    isData() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setData(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    getJson() {
        capnp_ts_1.Struct.testWhich("json", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isJson() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setJson(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    adoptWasmModule(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownWasmModule() { return capnp_ts_1.Struct.disown(this.getWasmModule()); }
    getWasmModule() {
        capnp_ts_1.Struct.testWhich("wasmModule", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getData(1, this);
    }
    hasWasmModule() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initWasmModule(length) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        return capnp_ts_1.Struct.initData(1, length, this);
    }
    isWasmModule() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setWasmModule(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptCryptoKey(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownCryptoKey() { return capnp_ts_1.Struct.disown(this.getCryptoKey()); }
    getCryptoKey() {
        capnp_ts_1.Struct.testWhich("cryptoKey", capnp_ts_1.Struct.getUint16(0, this), 6, this);
        return capnp_ts_1.Struct.getStruct(1, Worker_Binding_CryptoKey, this);
    }
    hasCryptoKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initCryptoKey() {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        return capnp_ts_1.Struct.initStructAt(1, Worker_Binding_CryptoKey, this);
    }
    isCryptoKey() { return capnp_ts_1.Struct.getUint16(0, this) === 6; }
    setCryptoKey(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptService(value) {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownService() { return capnp_ts_1.Struct.disown(this.getService()); }
    getService() {
        capnp_ts_1.Struct.testWhich("service", capnp_ts_1.Struct.getUint16(0, this), 7, this);
        return capnp_ts_1.Struct.getStruct(1, ServiceDesignator, this);
    }
    hasService() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initService() {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        return capnp_ts_1.Struct.initStructAt(1, ServiceDesignator, this);
    }
    isService() { return capnp_ts_1.Struct.getUint16(0, this) === 7; }
    setService(value) {
        capnp_ts_1.Struct.setUint16(0, 7, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptDurableObjectNamespace(value) {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownDurableObjectNamespace() { return capnp_ts_1.Struct.disown(this.getDurableObjectNamespace()); }
    getDurableObjectNamespace() {
        capnp_ts_1.Struct.testWhich("durableObjectNamespace", capnp_ts_1.Struct.getUint16(0, this), 8, this);
        return capnp_ts_1.Struct.getStruct(1, Worker_Binding_DurableObjectNamespaceDesignator, this);
    }
    hasDurableObjectNamespace() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initDurableObjectNamespace() {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        return capnp_ts_1.Struct.initStructAt(1, Worker_Binding_DurableObjectNamespaceDesignator, this);
    }
    isDurableObjectNamespace() { return capnp_ts_1.Struct.getUint16(0, this) === 8; }
    setDurableObjectNamespace(value) {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptKvNamespace(value) {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownKvNamespace() { return capnp_ts_1.Struct.disown(this.getKvNamespace()); }
    getKvNamespace() {
        capnp_ts_1.Struct.testWhich("kvNamespace", capnp_ts_1.Struct.getUint16(0, this), 9, this);
        return capnp_ts_1.Struct.getStruct(1, ServiceDesignator, this);
    }
    hasKvNamespace() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initKvNamespace() {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        return capnp_ts_1.Struct.initStructAt(1, ServiceDesignator, this);
    }
    isKvNamespace() { return capnp_ts_1.Struct.getUint16(0, this) === 9; }
    setKvNamespace(value) {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptR2Bucket(value) {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownR2Bucket() { return capnp_ts_1.Struct.disown(this.getR2Bucket()); }
    getR2Bucket() {
        capnp_ts_1.Struct.testWhich("r2Bucket", capnp_ts_1.Struct.getUint16(0, this), 10, this);
        return capnp_ts_1.Struct.getStruct(1, ServiceDesignator, this);
    }
    hasR2Bucket() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initR2Bucket() {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        return capnp_ts_1.Struct.initStructAt(1, ServiceDesignator, this);
    }
    isR2Bucket() { return capnp_ts_1.Struct.getUint16(0, this) === 10; }
    setR2Bucket(value) {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptR2Admin(value) {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownR2Admin() { return capnp_ts_1.Struct.disown(this.getR2Admin()); }
    getR2Admin() {
        capnp_ts_1.Struct.testWhich("r2Admin", capnp_ts_1.Struct.getUint16(0, this), 11, this);
        return capnp_ts_1.Struct.getStruct(1, ServiceDesignator, this);
    }
    hasR2Admin() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initR2Admin() {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        return capnp_ts_1.Struct.initStructAt(1, ServiceDesignator, this);
    }
    isR2Admin() { return capnp_ts_1.Struct.getUint16(0, this) === 11; }
    setR2Admin(value) {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptWrapped(value) {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownWrapped() { return capnp_ts_1.Struct.disown(this.getWrapped()); }
    getWrapped() {
        capnp_ts_1.Struct.testWhich("wrapped", capnp_ts_1.Struct.getUint16(0, this), 12, this);
        return capnp_ts_1.Struct.getStruct(1, Worker_Binding_WrappedBinding, this);
    }
    hasWrapped() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initWrapped() {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        return capnp_ts_1.Struct.initStructAt(1, Worker_Binding_WrappedBinding, this);
    }
    isWrapped() { return capnp_ts_1.Struct.getUint16(0, this) === 12; }
    setWrapped(value) {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    adoptQueue(value) {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownQueue() { return capnp_ts_1.Struct.disown(this.getQueue()); }
    getQueue() {
        capnp_ts_1.Struct.testWhich("queue", capnp_ts_1.Struct.getUint16(0, this), 13, this);
        return capnp_ts_1.Struct.getStruct(1, ServiceDesignator, this);
    }
    hasQueue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initQueue() {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        return capnp_ts_1.Struct.initStructAt(1, ServiceDesignator, this);
    }
    isQueue() { return capnp_ts_1.Struct.getUint16(0, this) === 13; }
    setQueue(value) {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    toString() { return "Worker_Binding_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Worker_Binding = Worker_Binding;
Worker_Binding.UNSPECIFIED = Worker_Binding_Which.UNSPECIFIED;
Worker_Binding.PARAMETER = Worker_Binding_Which.PARAMETER;
Worker_Binding.TEXT = Worker_Binding_Which.TEXT;
Worker_Binding.DATA = Worker_Binding_Which.DATA;
Worker_Binding.JSON = Worker_Binding_Which.JSON;
Worker_Binding.WASM_MODULE = Worker_Binding_Which.WASM_MODULE;
Worker_Binding.CRYPTO_KEY = Worker_Binding_Which.CRYPTO_KEY;
Worker_Binding.SERVICE = Worker_Binding_Which.SERVICE;
Worker_Binding.DURABLE_OBJECT_NAMESPACE = Worker_Binding_Which.DURABLE_OBJECT_NAMESPACE;
Worker_Binding.KV_NAMESPACE = Worker_Binding_Which.KV_NAMESPACE;
Worker_Binding.R2BUCKET = Worker_Binding_Which.R2BUCKET;
Worker_Binding.R2ADMIN = Worker_Binding_Which.R2ADMIN;
Worker_Binding.WRAPPED = Worker_Binding_Which.WRAPPED;
Worker_Binding.QUEUE = Worker_Binding_Which.QUEUE;
Worker_Binding.Type = Worker_Binding_Type;
Worker_Binding.DurableObjectNamespaceDesignator = Worker_Binding_DurableObjectNamespaceDesignator;
Worker_Binding.CryptoKey = Worker_Binding_CryptoKey;
Worker_Binding.WrappedBinding = Worker_Binding_WrappedBinding;
Worker_Binding._capnp = { displayName: "Binding", id: "8e7e492fd7e35f3e", size: new capnp_ts_1.ObjectSize(8, 2) };
var Worker_DurableObjectNamespace_Which;
(function (Worker_DurableObjectNamespace_Which) {
    Worker_DurableObjectNamespace_Which[Worker_DurableObjectNamespace_Which["UNIQUE_KEY"] = 0] = "UNIQUE_KEY";
    Worker_DurableObjectNamespace_Which[Worker_DurableObjectNamespace_Which["EPHEMERAL_LOCAL"] = 1] = "EPHEMERAL_LOCAL";
})(Worker_DurableObjectNamespace_Which = exports.Worker_DurableObjectNamespace_Which || (exports.Worker_DurableObjectNamespace_Which = {}));
class Worker_DurableObjectNamespace extends capnp_ts_1.Struct {
    getClassName() { return capnp_ts_1.Struct.getText(0, this); }
    setClassName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getUniqueKey() {
        capnp_ts_1.Struct.testWhich("uniqueKey", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isUniqueKey() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setUniqueKey(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    isEphemeralLocal() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setEphemeralLocal() { capnp_ts_1.Struct.setUint16(0, 1, this); }
    toString() { return "Worker_DurableObjectNamespace_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Worker_DurableObjectNamespace = Worker_DurableObjectNamespace;
Worker_DurableObjectNamespace.UNIQUE_KEY = Worker_DurableObjectNamespace_Which.UNIQUE_KEY;
Worker_DurableObjectNamespace.EPHEMERAL_LOCAL = Worker_DurableObjectNamespace_Which.EPHEMERAL_LOCAL;
Worker_DurableObjectNamespace._capnp = { displayName: "DurableObjectNamespace", id: "b429dd547d15747d", size: new capnp_ts_1.ObjectSize(8, 2) };
var Worker_DurableObjectStorage_Which;
(function (Worker_DurableObjectStorage_Which) {
    Worker_DurableObjectStorage_Which[Worker_DurableObjectStorage_Which["NONE"] = 0] = "NONE";
    Worker_DurableObjectStorage_Which[Worker_DurableObjectStorage_Which["IN_MEMORY"] = 1] = "IN_MEMORY";
    Worker_DurableObjectStorage_Which[Worker_DurableObjectStorage_Which["LOCAL_DISK"] = 2] = "LOCAL_DISK";
})(Worker_DurableObjectStorage_Which = exports.Worker_DurableObjectStorage_Which || (exports.Worker_DurableObjectStorage_Which = {}));
class Worker_DurableObjectStorage extends capnp_ts_1.Struct {
    isNone() { return capnp_ts_1.Struct.getUint16(2, this) === 0; }
    setNone() { capnp_ts_1.Struct.setUint16(2, 0, this); }
    isInMemory() { return capnp_ts_1.Struct.getUint16(2, this) === 1; }
    setInMemory() { capnp_ts_1.Struct.setUint16(2, 1, this); }
    getLocalDisk() {
        capnp_ts_1.Struct.testWhich("localDisk", capnp_ts_1.Struct.getUint16(2, this), 2, this);
        return capnp_ts_1.Struct.getText(8, this);
    }
    isLocalDisk() { return capnp_ts_1.Struct.getUint16(2, this) === 2; }
    setLocalDisk(value) {
        capnp_ts_1.Struct.setUint16(2, 2, this);
        capnp_ts_1.Struct.setText(8, value, this);
    }
    toString() { return "Worker_DurableObjectStorage_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(2, this); }
}
exports.Worker_DurableObjectStorage = Worker_DurableObjectStorage;
Worker_DurableObjectStorage.NONE = Worker_DurableObjectStorage_Which.NONE;
Worker_DurableObjectStorage.IN_MEMORY = Worker_DurableObjectStorage_Which.IN_MEMORY;
Worker_DurableObjectStorage.LOCAL_DISK = Worker_DurableObjectStorage_Which.LOCAL_DISK;
Worker_DurableObjectStorage._capnp = { displayName: "durableObjectStorage", id: "cc72b3faa57827d4", size: new capnp_ts_1.ObjectSize(8, 9) };
var Worker_Which;
(function (Worker_Which) {
    Worker_Which[Worker_Which["MODULES"] = 0] = "MODULES";
    Worker_Which[Worker_Which["SERVICE_WORKER_SCRIPT"] = 1] = "SERVICE_WORKER_SCRIPT";
    Worker_Which[Worker_Which["INHERIT"] = 2] = "INHERIT";
})(Worker_Which = exports.Worker_Which || (exports.Worker_Which = {}));
class Worker extends capnp_ts_1.Struct {
    adoptModules(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownModules() { return capnp_ts_1.Struct.disown(this.getModules()); }
    getModules() {
        capnp_ts_1.Struct.testWhich("modules", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getList(0, Worker._Modules, this);
    }
    hasModules() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initModules(length) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initList(0, Worker._Modules, length, this);
    }
    isModules() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setModules(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    getServiceWorkerScript() {
        capnp_ts_1.Struct.testWhich("serviceWorkerScript", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isServiceWorkerScript() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setServiceWorkerScript(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getInherit() {
        capnp_ts_1.Struct.testWhich("inherit", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getText(0, this);
    }
    isInherit() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setInherit(value) {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        capnp_ts_1.Struct.setText(0, value, this);
    }
    getCompatibilityDate() { return capnp_ts_1.Struct.getText(1, this); }
    setCompatibilityDate(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptCompatibilityFlags(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownCompatibilityFlags() { return capnp_ts_1.Struct.disown(this.getCompatibilityFlags()); }
    getCompatibilityFlags() { return capnp_ts_1.Struct.getList(2, capnp.TextList, this); }
    hasCompatibilityFlags() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initCompatibilityFlags(length) { return capnp_ts_1.Struct.initList(2, capnp.TextList, length, this); }
    setCompatibilityFlags(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptBindings(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownBindings() { return capnp_ts_1.Struct.disown(this.getBindings()); }
    getBindings() { return capnp_ts_1.Struct.getList(3, Worker._Bindings, this); }
    hasBindings() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initBindings(length) { return capnp_ts_1.Struct.initList(3, Worker._Bindings, length, this); }
    setBindings(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptGlobalOutbound(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownGlobalOutbound() { return capnp_ts_1.Struct.disown(this.getGlobalOutbound()); }
    getGlobalOutbound() { return capnp_ts_1.Struct.getStruct(4, ServiceDesignator, this, Worker._capnp.defaultGlobalOutbound); }
    hasGlobalOutbound() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initGlobalOutbound() { return capnp_ts_1.Struct.initStructAt(4, ServiceDesignator, this); }
    setGlobalOutbound(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptCacheApiOutbound(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(7, this)); }
    disownCacheApiOutbound() { return capnp_ts_1.Struct.disown(this.getCacheApiOutbound()); }
    getCacheApiOutbound() { return capnp_ts_1.Struct.getStruct(7, ServiceDesignator, this); }
    hasCacheApiOutbound() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(7, this)); }
    initCacheApiOutbound() { return capnp_ts_1.Struct.initStructAt(7, ServiceDesignator, this); }
    setCacheApiOutbound(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(7, this)); }
    adoptDurableObjectNamespaces(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownDurableObjectNamespaces() { return capnp_ts_1.Struct.disown(this.getDurableObjectNamespaces()); }
    getDurableObjectNamespaces() { return capnp_ts_1.Struct.getList(5, Worker._DurableObjectNamespaces, this); }
    hasDurableObjectNamespaces() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initDurableObjectNamespaces(length) { return capnp_ts_1.Struct.initList(5, Worker._DurableObjectNamespaces, length, this); }
    setDurableObjectNamespaces(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    getDurableObjectUniqueKeyModifier() { return capnp_ts_1.Struct.getText(6, this); }
    setDurableObjectUniqueKeyModifier(value) { capnp_ts_1.Struct.setText(6, value, this); }
    getDurableObjectStorage() { return capnp_ts_1.Struct.getAs(Worker_DurableObjectStorage, this); }
    initDurableObjectStorage() { return capnp_ts_1.Struct.getAs(Worker_DurableObjectStorage, this); }
    toString() { return "Worker_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Worker = Worker;
Worker.MODULES = Worker_Which.MODULES;
Worker.SERVICE_WORKER_SCRIPT = Worker_Which.SERVICE_WORKER_SCRIPT;
Worker.INHERIT = Worker_Which.INHERIT;
Worker.Module = Worker_Module;
Worker.Binding = Worker_Binding;
Worker.DurableObjectNamespace = Worker_DurableObjectNamespace;
Worker._capnp = { displayName: "Worker", id: "acfa77e88fd97d1c", size: new capnp_ts_1.ObjectSize(8, 9), defaultGlobalOutbound: capnp.readRawPointer(new Uint8Array([0x10, 0x05, 0x40, 0x02, 0x11, 0x05, 0x4a, 0x00, 0x00, 0xff, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x00, 0x00, 0x00]).buffer) };
class ExternalServer_Https extends capnp_ts_1.Struct {
    adoptOptions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownOptions() { return capnp_ts_1.Struct.disown(this.getOptions()); }
    getOptions() { return capnp_ts_1.Struct.getStruct(1, HttpOptions, this); }
    hasOptions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initOptions() { return capnp_ts_1.Struct.initStructAt(1, HttpOptions, this); }
    setOptions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptTlsOptions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownTlsOptions() { return capnp_ts_1.Struct.disown(this.getTlsOptions()); }
    getTlsOptions() { return capnp_ts_1.Struct.getStruct(2, TlsOptions, this); }
    hasTlsOptions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initTlsOptions() { return capnp_ts_1.Struct.initStructAt(2, TlsOptions, this); }
    setTlsOptions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getCertificateHost() { return capnp_ts_1.Struct.getText(3, this); }
    setCertificateHost(value) { capnp_ts_1.Struct.setText(3, value, this); }
    toString() { return "ExternalServer_Https_" + super.toString(); }
}
exports.ExternalServer_Https = ExternalServer_Https;
ExternalServer_Https._capnp = { displayName: "https", id: "ac37e02afd3dc6db", size: new capnp_ts_1.ObjectSize(8, 4) };
var ExternalServer_Which;
(function (ExternalServer_Which) {
    ExternalServer_Which[ExternalServer_Which["HTTP"] = 0] = "HTTP";
    ExternalServer_Which[ExternalServer_Which["HTTPS"] = 1] = "HTTPS";
})(ExternalServer_Which = exports.ExternalServer_Which || (exports.ExternalServer_Which = {}));
class ExternalServer extends capnp_ts_1.Struct {
    getAddress() { return capnp_ts_1.Struct.getText(0, this); }
    setAddress(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptHttp(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    disownHttp() { return capnp_ts_1.Struct.disown(this.getHttp()); }
    getHttp() {
        capnp_ts_1.Struct.testWhich("http", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(1, HttpOptions, this);
    }
    hasHttp() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initHttp() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(1, HttpOptions, this);
    }
    isHttp() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setHttp(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this));
    }
    getHttps() {
        capnp_ts_1.Struct.testWhich("https", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getAs(ExternalServer_Https, this);
    }
    initHttps() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.getAs(ExternalServer_Https, this);
    }
    isHttps() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setHttps() { capnp_ts_1.Struct.setUint16(0, 1, this); }
    toString() { return "ExternalServer_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.ExternalServer = ExternalServer;
ExternalServer.HTTP = ExternalServer_Which.HTTP;
ExternalServer.HTTPS = ExternalServer_Which.HTTPS;
ExternalServer._capnp = { displayName: "ExternalServer", id: "ff209f9aa352f5a4", size: new capnp_ts_1.ObjectSize(8, 4) };
class Network extends capnp_ts_1.Struct {
    adoptAllow(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownAllow() { return capnp_ts_1.Struct.disown(this.getAllow()); }
    getAllow() { return capnp_ts_1.Struct.getList(0, capnp.TextList, this, Network._capnp.defaultAllow); }
    hasAllow() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initAllow(length) { return capnp_ts_1.Struct.initList(0, capnp.TextList, length, this); }
    setAllow(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptDeny(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownDeny() { return capnp_ts_1.Struct.disown(this.getDeny()); }
    getDeny() { return capnp_ts_1.Struct.getList(1, capnp.TextList, this); }
    hasDeny() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initDeny(length) { return capnp_ts_1.Struct.initList(1, capnp.TextList, length, this); }
    setDeny(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptTlsOptions(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownTlsOptions() { return capnp_ts_1.Struct.disown(this.getTlsOptions()); }
    getTlsOptions() { return capnp_ts_1.Struct.getStruct(2, TlsOptions, this); }
    hasTlsOptions() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initTlsOptions() { return capnp_ts_1.Struct.initStructAt(2, TlsOptions, this); }
    setTlsOptions(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "Network_" + super.toString(); }
}
exports.Network = Network;
Network._capnp = { displayName: "Network", id: "fa42244f950c9b9c", size: new capnp_ts_1.ObjectSize(0, 3), defaultAllow: capnp.readRawPointer(new Uint8Array([0x10, 0x03, 0x11, 0x01, 0x0e, 0x11, 0x01, 0x3a, 0x3f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63]).buffer) };
class DiskDirectory extends capnp_ts_1.Struct {
    getPath() { return capnp_ts_1.Struct.getText(0, this); }
    setPath(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getWritable() { return capnp_ts_1.Struct.getBit(0, this, DiskDirectory._capnp.defaultWritable); }
    setWritable(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getAllowDotfiles() { return capnp_ts_1.Struct.getBit(1, this, DiskDirectory._capnp.defaultAllowDotfiles); }
    setAllowDotfiles(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    toString() { return "DiskDirectory_" + super.toString(); }
}
exports.DiskDirectory = DiskDirectory;
DiskDirectory._capnp = { displayName: "DiskDirectory", id: "9048ab22835f51c3", size: new capnp_ts_1.ObjectSize(8, 1), defaultWritable: capnp.getBitMask(false, 0), defaultAllowDotfiles: capnp.getBitMask(false, 1) };
var HttpOptions_Style;
(function (HttpOptions_Style) {
    HttpOptions_Style[HttpOptions_Style["HOST"] = 0] = "HOST";
    HttpOptions_Style[HttpOptions_Style["PROXY"] = 1] = "PROXY";
})(HttpOptions_Style = exports.HttpOptions_Style || (exports.HttpOptions_Style = {}));
class HttpOptions_Header extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getValue() { return capnp_ts_1.Struct.getText(1, this); }
    setValue(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "HttpOptions_Header_" + super.toString(); }
}
exports.HttpOptions_Header = HttpOptions_Header;
HttpOptions_Header._capnp = { displayName: "Header", id: "dc0394b5a6f3417e", size: new capnp_ts_1.ObjectSize(0, 2) };
class HttpOptions extends capnp_ts_1.Struct {
    getStyle() { return capnp_ts_1.Struct.getUint16(0, this, HttpOptions._capnp.defaultStyle); }
    setStyle(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    getForwardedProtoHeader() { return capnp_ts_1.Struct.getText(0, this); }
    setForwardedProtoHeader(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getCfBlobHeader() { return capnp_ts_1.Struct.getText(1, this); }
    setCfBlobHeader(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptInjectRequestHeaders(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownInjectRequestHeaders() { return capnp_ts_1.Struct.disown(this.getInjectRequestHeaders()); }
    getInjectRequestHeaders() { return capnp_ts_1.Struct.getList(2, HttpOptions._InjectRequestHeaders, this); }
    hasInjectRequestHeaders() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initInjectRequestHeaders(length) { return capnp_ts_1.Struct.initList(2, HttpOptions._InjectRequestHeaders, length, this); }
    setInjectRequestHeaders(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptInjectResponseHeaders(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownInjectResponseHeaders() { return capnp_ts_1.Struct.disown(this.getInjectResponseHeaders()); }
    getInjectResponseHeaders() { return capnp_ts_1.Struct.getList(3, HttpOptions._InjectResponseHeaders, this); }
    hasInjectResponseHeaders() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initInjectResponseHeaders(length) { return capnp_ts_1.Struct.initList(3, HttpOptions._InjectResponseHeaders, length, this); }
    setInjectResponseHeaders(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "HttpOptions_" + super.toString(); }
}
exports.HttpOptions = HttpOptions;
HttpOptions.Style = HttpOptions_Style;
HttpOptions.Header = HttpOptions_Header;
HttpOptions._capnp = { displayName: "HttpOptions", id: "aa8dc6885da78f19", size: new capnp_ts_1.ObjectSize(8, 4), defaultStyle: capnp.getUint16Mask(0) };
class TlsOptions_Keypair extends capnp_ts_1.Struct {
    getPrivateKey() { return capnp_ts_1.Struct.getText(0, this); }
    setPrivateKey(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getCertificateChain() { return capnp_ts_1.Struct.getText(1, this); }
    setCertificateChain(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "TlsOptions_Keypair_" + super.toString(); }
}
exports.TlsOptions_Keypair = TlsOptions_Keypair;
TlsOptions_Keypair._capnp = { displayName: "Keypair", id: "f546bf2d5d8bd13e", size: new capnp_ts_1.ObjectSize(0, 2) };
var TlsOptions_Version;
(function (TlsOptions_Version) {
    TlsOptions_Version[TlsOptions_Version["GOOD_DEFAULT"] = 0] = "GOOD_DEFAULT";
    TlsOptions_Version[TlsOptions_Version["SSL3"] = 1] = "SSL3";
    TlsOptions_Version[TlsOptions_Version["TLS1DOT0"] = 2] = "TLS1DOT0";
    TlsOptions_Version[TlsOptions_Version["TLS1DOT1"] = 3] = "TLS1DOT1";
    TlsOptions_Version[TlsOptions_Version["TLS1DOT2"] = 4] = "TLS1DOT2";
    TlsOptions_Version[TlsOptions_Version["TLS1DOT3"] = 5] = "TLS1DOT3";
})(TlsOptions_Version = exports.TlsOptions_Version || (exports.TlsOptions_Version = {}));
class TlsOptions extends capnp_ts_1.Struct {
    adoptKeypair(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKeypair() { return capnp_ts_1.Struct.disown(this.getKeypair()); }
    getKeypair() { return capnp_ts_1.Struct.getStruct(0, TlsOptions_Keypair, this); }
    hasKeypair() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKeypair() { return capnp_ts_1.Struct.initStructAt(0, TlsOptions_Keypair, this); }
    setKeypair(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getRequireClientCerts() { return capnp_ts_1.Struct.getBit(0, this, TlsOptions._capnp.defaultRequireClientCerts); }
    setRequireClientCerts(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getTrustBrowserCas() { return capnp_ts_1.Struct.getBit(1, this, TlsOptions._capnp.defaultTrustBrowserCas); }
    setTrustBrowserCas(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    adoptTrustedCertificates(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownTrustedCertificates() { return capnp_ts_1.Struct.disown(this.getTrustedCertificates()); }
    getTrustedCertificates() { return capnp_ts_1.Struct.getList(1, capnp.TextList, this); }
    hasTrustedCertificates() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initTrustedCertificates(length) { return capnp_ts_1.Struct.initList(1, capnp.TextList, length, this); }
    setTrustedCertificates(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getMinVersion() { return capnp_ts_1.Struct.getUint16(2, this, TlsOptions._capnp.defaultMinVersion); }
    setMinVersion(value) { capnp_ts_1.Struct.setUint16(2, value, this); }
    getCipherList() { return capnp_ts_1.Struct.getText(2, this); }
    setCipherList(value) { capnp_ts_1.Struct.setText(2, value, this); }
    toString() { return "TlsOptions_" + super.toString(); }
}
exports.TlsOptions = TlsOptions;
TlsOptions.Keypair = TlsOptions_Keypair;
TlsOptions.Version = TlsOptions_Version;
TlsOptions._capnp = { displayName: "TlsOptions", id: "aabb3c3778ac4311", size: new capnp_ts_1.ObjectSize(8, 3), defaultRequireClientCerts: capnp.getBitMask(false, 0), defaultTrustBrowserCas: capnp.getBitMask(false, 1), defaultMinVersion: capnp.getUint16Mask(0) };
class Extension_Module extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getInternal() { return capnp_ts_1.Struct.getBit(0, this, Extension_Module._capnp.defaultInternal); }
    setInternal(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getEsModule() { return capnp_ts_1.Struct.getText(1, this); }
    setEsModule(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "Extension_Module_" + super.toString(); }
}
exports.Extension_Module = Extension_Module;
Extension_Module._capnp = { displayName: "Module", id: "d5d16e76fdedc37d", size: new capnp_ts_1.ObjectSize(8, 2), defaultInternal: capnp.getBitMask(false, 0) };
class Extension extends capnp_ts_1.Struct {
    adoptModules(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownModules() { return capnp_ts_1.Struct.disown(this.getModules()); }
    getModules() { return capnp_ts_1.Struct.getList(0, Extension._Modules, this); }
    hasModules() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initModules(length) { return capnp_ts_1.Struct.initList(0, Extension._Modules, length, this); }
    setModules(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Extension_" + super.toString(); }
}
exports.Extension = Extension;
Extension.Module = Extension_Module;
Extension._capnp = { displayName: "Extension", id: "e390128a861973a6", size: new capnp_ts_1.ObjectSize(0, 1) };
Config._Services = capnp.CompositeList(Service);
Config._Sockets = capnp.CompositeList(Socket);
Config._Extensions = capnp.CompositeList(Extension);
Worker_Binding_WrappedBinding._InnerBindings = capnp.CompositeList(Worker_Binding);
Worker._Modules = capnp.CompositeList(Worker_Module);
Worker._Bindings = capnp.CompositeList(Worker_Binding);
Worker._DurableObjectNamespaces = capnp.CompositeList(Worker_DurableObjectNamespace);
HttpOptions._InjectRequestHeaders = capnp.CompositeList(HttpOptions_Header);
HttpOptions._InjectResponseHeaders = capnp.CompositeList(HttpOptions_Header);
Extension._Modules = capnp.CompositeList(Extension_Module);
