name: Add issues to DevProd project

on:
  issues:
    types: [opened, labeled, unlabeled, transferred]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/cloudflare/projects/1
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
